version: "3"
services:
  lotus:
    build:
      context: .
      args:
        - BRANCH
        - NETWORK
    image: 'glif/lotus:latest'
    env_file:
      - .env
    user: lotus_user
    volumes:
      - $HOME/lotus:/home/lotus_user
    ports:
      - "1234:1234"
      - "1235:1235"
