version: "3"
services:
  lotus:
    build:
      context: .
      args:
        - BRANCH=master
        - NETWORK=nerpanet
    image: 'glif/lotus:master'
    environment:
     - INFRA_LOTUS_DAEMON=true
     - INFRA_LOTUS_HOME=/home/lotus_user
     - INFRA_IMPORT_SNAPSHOT=true
     - SNAPSHOTURL=https://dev.node.glif.io/nerpa00/ipfs/8080/ipfs/QmWCpnE28HGma5SgGYQbVdeuMbbLoRmk1dhz2fQi6vUr5Q
     - INFRA_SYNC=true
    volumes:
      - type: bind
        source: $HOME/lotus
        target: /home/lotus_user
    ports:
      - "1234:1234"
      - "1235:1235"
